### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [developit/preact-render-to-string#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by developit** [comment]
Good catch. I'm so used to my module boilerplate throwing an MIT license on everything I missed it this time! :)

https://github.com/developit/preact-render-to-string#license
https://github.com/developit/preact-render-to-string/blob/master/LICENSE
