### ISSUE TITLE
Does not work w/ preact-compat components

### ISSUE THREAD

**Issue by dmitrif** [developit/preact-render-to-string#12]
Components instantiated using React style (extends Component) and while aliasing React to point at react-compat render as `[object Object]`.  Reason being is that components instantiated using react-compat do not have a `nodename`:

```javascript
{ '$$typeof': Symbol(react.element),
  type:
   { [Function: Footer]
     childContextTypes: { intl: [Object], locale: [Object] },
     displayName: 'Footer',
     modulePath: '/app/components/Shared/Footer' },
  key: null,
  ref: null,
  props:
   { store:
      { dispatch: [Function],
        subscribe: [Function: subscribe],
        getState: [Function: getState],
        replaceReducer: [Function: replaceReducer] },
     intl: { [Function] cache: [Object], toString: [Function], format: [Function] },
     locale: 'en-CA',
     dispatch: [Function] },
  _owner: null }
```

Resulting in the following code being triggered in `renderToString`:
```javascript
if (!nodeName) {
    return encodeEntities(vnode);
}
```

**Comment by developit** [comment]
@dmitrif It actually looks like you're passing in a React VNode, not a preact-compat VNode. Are you sure your alias is working?

**Comment by developit** [comment]
@dmitrif Here's a demonstration showing that what you described works:
https://jsfiddle.net/developit/w13rh1f4/

It definitely looks like you've got a configuration issue somewhere (webpack aliases?) that is resulting in React still being used to create the Virtual DOM Elements instead of preact-compat.

Let me know if you're able to verify.

**Comment by dmitrif** [comment]
Seems you are absolutely correct. For some reason I was convinced that the aliasing was happening correctly, but after grokking through the compiled server code, I was proven wrong.

Thank you for your time :)

**Comment by developit** [comment]
No problem! Feel free to drop into the [Preact Gitter Chat](https://gitter.im/developit/preact) if you are still having issues with the alias!
