### ISSUE TITLE
Add option to render empty attributes

### ISSUE THREAD

**Issue by wyze** [developit/preact-render-to-string#17]
I use [`glamor`](https://github.com/threepointone/glamor) for styling which renders data attributes for its css selectors. It looks like there was a change in `v2.20.x` that removed the values of the data attributes. It now produces html as the following:

```html
<div data-css-19swgx6 />
```

The server rendering tests in `glamor` pass, so I assume that `renderToStaticMarkup` from `react-server/dom` renders the empty attributes, so it would be nice to have this as a little compatibility layer as well. Tracking this down, I was able to modify their tests to use render using this library and verified that the empty attributes weren't rendered, causing their tests to fail.

I've tracked it down to [src/index.js#L137](https://github.com/developit/preact-render-to-string/blob/master/src/index.js#L137) which omits falsey values.

I am curious if this is an option you would consider adding? If so, I would be happy to submit a PR to add this as an opt-in feature.

**Comment by developit** [comment]
Hi @wyze - do you know what the value glamor provides is?  If it's an empty String that seems like an easy fix.

**Comment by wyze** [comment]
Yes, it now defaults to an empty string. See the false case in this ternary expression here: https://github.com/threepointone/glamor/blob/v2.20.12/src/index.js#L234

**Comment by developit** [comment]
Perfect! That's an easy and worthwhile fix then.

**Comment by developit** [comment]
Released as [3.4.0](https://github.com/developit/preact-render-to-string/releases/tag/3.4.0).
