### ISSUE TITLE
how to configure with preact-compat ?

### ISSUE THREAD

**Issue by budarin** [developit/preact-render-to-string#20]
I configured project as described in preact-compat

```
import React from 'react';
import render from 'preact-render-to-string';
import App from '../common/components/App.jsx';
import Container from '../common/components/Container.jsx';

export default function serverEntry() {
    return render(
        <Container>
            <App />
        </Container>
    );
};
```
when run - error throws: ReferenceError: h is not defined

using 'import { h } from 'preact'' instead of 'import React from 'react'' - doesn't help

**Comment by developit** [comment]
When using preact-compat, you no longer need the custom jsx pragma in your Babel config. Just use the React preset or remove the pragma option. 

Also, `preact-compat` already includes `preact-render-to-string` for you. 

```js
.
```

**Comment by dodekeract** [comment]
@developit @budarin I think this issue can be closed.
