### ISSUE TITLE
Render KML

### ISSUE THREAD

**Issue by Scarysize** [developit/preact-render-to-string#22]
I want to render [KML](https://en.wikipedia.org/wiki/Keyhole_Markup_Language) using this, but I'm running into problems.

I have something like this

```js
const folder = props => (
  <Folder>
    {props.children}
  </Folder>
);

const KML = () => (
  <kml>
    <folder>
      foo
    </folder>
  </kml>
);
```

What I want as output:

```xml
<kml>
  <Folder>
    foo
  </Folder>
</kml>
```

What I get is:

```xml
  <kml>
    <folder>
      foo
    </folder>
  </kml>
```

I passed `xml: true` to `renderToString`.

Is there a convention in the casing of JSX tags?

**Comment by developit** [comment]
Might need to add a bypass around the tag lowercasing in XML mode, or a dedicated option 'lowercase:false`

**Comment by Scarysize** [comment]
That would be much appreciated!

**Comment by developit** [comment]
@Scarysize I'll add it to the existing XML mode so that it'll "just work" for you once released.

**Comment by Scarysize** [comment]
Sounds great, no hurry!

**Comment by developit** [comment]
Hi @Scarysize - it actually looks like rendering uppercase tags is already supported, just it's not a feature of JSX (which we can't change).  You'll have to do something like this:

```js
const Folder = 'Folder';

const KML = () => (
  <kml>
    <Folder>
      foo
    </Folder>
  </kml>
);
```

... which is easier to understand when you look at what that transpiles to:

```js
const Folder = 'Folder';

const KML = () => (
  h('kml', null,
    h(Folder, null,
      'foo'
    )
  )
);
```
