### ISSUE TITLE
Void elements render without a closing /

### ISSUE THREAD

**Issue by elliotdavies** [developit/preact-render-to-string#24]
Currently the behaviour for void elements (`img`, `br`, etc) is that they render without a closing `/` – for example, `<br>` instead of `<br/>`.

Unfortunately this closing `/` is required for XHTML, meaning a Preact render won't validate against that content type. It's also a possible compatibility issue when using `preact-compat`, since React's own `renderToString` method adds the `/`.

The `/` is optional in HTML5, so I think rendering it out should resolve the above issues without breaking anything.

If this looks like a good idea, I'd be happy to submit a PR.

Thanks!

**Comment by developit** [comment]
@elliotdavies would that let us drop the whitelist of self-closing elements?  If so, I'm 100% in favor of always outputting `/` for void elements.  Happy to merge that PR if you're good to create it.

**Comment by elliotdavies** [comment]
@developit Not that I can see – you still need some way to know whether to self-close e.g. `<br/>` or instead do a full closing tag e.g. `<div>...</div>`, and I think a whitelist is the only reliable way to check that.

Still, this should be a pretty minimal change. I'll write up the PR and you can take a look.

**Comment by developit** [comment]
Works for me.

**Comment by Download** [comment]
Lol I was just changing the tests for preact-helmet to take this difference into account but it looks like I'm going to have to be changing them back pretty soon...

**Comment by developit** [comment]
@Download that's odd - how come you had to change the tests?  If you're rendering JSX to strings in tests, I'd recommend using `preact-render-to-string/jsx` - it preserves non-string props.

**Comment by Download** [comment]
I am porting [react-helmet](https://github.com/nfl/react-helmet) to preact. It's tests tend to render some component, then check that the output matches some literal string.

I noticed two big differences with the output from Preact vs the one expected in the tests:

1. React outputs `="true"` for boolean properties, but Preact does not (I actually prefer Preact's more concise style). E.g. `<meta data-preact-helmet="true" ... />` vs `<meta data-preact-helmet ... />`
2. React self-closes elements that Preact does/did not. E.g: `<base href="https://localhost"/>` vs `<base href="https://localhost">`

Another really weird thing that is biting me is the way components are unmounted... It seems to be happening lazily in Preact? I have tests failing because `componentWillUnmount` wasn't called yet though the test expects it.... but Preact always seems to call it in time, *before* the new component is mounted... Anyway I am planning on committing it in this state and logging an issue here because I've been stuck on it for hours already.

**Comment by developit** [comment]
@Download `render()` + `innerHTML` would actually return `/` depending on if the document was XHTML or HTML.

**Comment by Download** [comment]
@developit Yes I think it's just `renderToString` which makes it shorter. The test is using/testing both forms. But it's also most important for `renderToString` to be short (to get low TTI). So even though it is annoying when testing that both Strings are subtly different, I think it is an advantage for Preact to keep it this way.

It might be interesting to have a test that just renders all kinds of markups in both ways and compare. Only differences that are beneficial should stay (or maybe give `renderToString` a flag to toggle).

**Comment by developit** [comment]
Flag to toggle would be good, that way it has the option to return either XHTML or HTML.

**Comment by elliotdavies** [comment]
Hi @developit – just wondering if there's any chance you could bump the release version so as to include this?

**Comment by developit** [comment]
Can do, yup.

**Comment by developit** [comment]
Released as [3.6.0](https://github.com/developit/preact-render-to-string/releases/tag/3.6.0)!

**Comment by elliotdavies** [comment]
Thanks!

**Comment by brandonpittman** [comment]
When using htm, the auto slash feature doesn't seem to work. Unclosed elements return `undefined` in the output.

**Comment by marvinhagemeister** [comment]
@brandonpittman Just to clarify: Are you using `preact-render-to-string` in combination with `htm`?

**Comment by brandonpittman** [comment]
@marvinhagemeister Yep.

**Comment by marvinhagemeister** [comment]
@brandonpittman Can you share a snippet or a codesandbox which shows the problem?

**Comment by marvinhagemeister** [comment]
@brandonpittman Just spoke with @jviide which is the maintainer of `htm`. Unclosed `void` elements are not supported in `htm` and therefore will lead to undefined behaviour. In `htm` you must always use a closing `/`.

**Comment by brandonpittman** [comment]
@marvinhagemeister Yeah, I figured that out on my own. Wasted a lot of time figuring it out though. ☹️

**Comment by marvinhagemeister** [comment]
@brandonpittman Did you import `preact/debug` somewhere? That's where all our debug warnings are and it should catch `undefined` vnodes. It only needs to be included once (best at the top of your app, before rendering starts).
