### ISSUE TITLE
Getting a TypeError: preact_render_to_string_1.default is not a function when using with ts

### ISSUE THREAD

**Issue by valotas** [developit/preact-render-to-string#28]
I do not know if that is a transpilation problem, but it looks like that when you try to do the following with typescript: 

```
import xyz from "module-with-default-export"
 ``` 

it assumes that a `exports.default` exists within `module-with-default-export`, which I think is right but it has been a while since I last checked the modules spec. It looks like `preact-render-to-string` directly exports a function.

Workaround is to do an:

```
import * as render from "preact-render-to-string"
``` 

But this is schematically wrong if I'm not mistaken.

**Comment by developit** [comment]
This depends on the rest of your setup - are you using webpack? (1 or 2?)

**Comment by valotas** [comment]
I'm just transpiling with ts and then run tests against the transpiled files. Nothing in between (no babel, no webpack, no browserify).

**Comment by developit** [comment]
Hmm - this module is a commonjs module, so the default export is a function.  Like any commonjs module, you'll need to use the alternative import syntax so that TypeScript doesn't look for `.default`:

https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

**Comment by marvinhagemeister** [comment]
Yep, this is the default behaviour of TypeScript for commonjs modules. `default` exports only exists for es6 modules. There is nothing we can do on our end here. Perhaps when TypeScript supports the `module` or `jsnext:main` field inside `package.json` things would change. Currently TypeScript follows the file listed in `main` and that is the commonjs module.

**Comment by DevanB** [comment]
I was getting this error and did `import * as render from 'preact-render-to-string'` to get it working. Hope that helps!

**Comment by developit** [comment]
This should be fixed since we ship ES Modules now.
