### ISSUE TITLE
[SyntaxError] "Unexpected token <" [render(<App/>)]

### ISSUE THREAD

**Issue by Mathieu-R** [developit/preact-render-to-string#29]
I've got this error when I launch my node server : 

```
    content: render(<App/>)
                    ^
SyntaxError: Unexpected token <
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
```

Here's a sample of my server.js file _(didn't show all the requires for instance)_.     
I don't know what's wrong.
You can see I use `preact-render-to-string` and pass this rendering to my handlebar template.

The same technique is used there : [https://github.com/jakearchibald/big-web-quiz/blob/master/server/views.js](url)     

```js
const handlebars = require('handlebars');
const render = require('preact-render-to-string');
const index = require('../front/index');
/** @jsx h */

app.get('/', (req, res) => {
  res.send(index({
    css: ['/static/style.css'],
    lazyCss: ['/static/style.css'],
    scripts: ['/static/build.js'],
    content: render(<App/>)
  }));
});
```

**Comment by developit** [comment]
Hi there - you need to transpile this with Babel, since you're using the [JSX Syntax](https://facebook.github.io/jsx/).  If you already have Babel set up, it's likely you're just missing the [babel-plugin-transform-react-jsx](https://www.npmjs.com/package/babel-plugin-transform-react-jsx) plugin. In your `.babelrc`:


```js
{
  "plugins": [
    ["transform-react-jsx", { "pragma": "h" }]
  ]
}
```

**Comment by Mathieu-R** [comment]
Oh sorry, didn't know I had to transpile my node code.

I saw that it was apparently a bad practice to transpile the "back-end code".

I suppose there's no any other way to do "react server-side-rendering" without transpiration ?

**Comment by developit** [comment]
There is: you can use the hyperscript function (`h()`) directly instead of JSX, or something like [HyperX or t7](https://github.com/developit/preact/issues/317#issuecomment-247476435), which use template strings instead of JSX.

```js
const handlebars = require('handlebars');
const render = require('preact-render-to-string');
const index = require('../front/index');

app.get('/', (req, res) => {
  res.send(index({
    css: ['/static/style.css'],
    lazyCss: ['/static/style.css'],
    scripts: ['/static/build.js'],
    content: render( h(App) )   // h() usage
  }));
});
```

**Comment by Mathieu-R** [comment]
Thanks :)

**Comment by NCorreia100** [comment]
I know what you mean being a bad practice to compile the server code.
Unless in special circumstances, you would only have to transpile the client code and when transpiling with babel, including code from other directories wouldn't make any sense.
However there are cases in which you would need to compile the sever code such as in server-side rendering.
