### ISSUE TITLE
doesn't work with react-ab-test

### ISSUE THREAD

**Issue by rossPatton** [developit/preact-render-to-string#32]
All components currently being ab-tested just end up rendering [object Object]. This only happens on the server side, so it's not a problem with preact

Is this known already? (and is there a workaround?) It appears to be the only thing blocking me from using preact

**Comment by developit** [comment]
@rossPatton That is usually caused by an alias not working - `preact-render-to-string` is being passed a React element but it only supports Preact ones.  How are you aliasing?

**Comment by rossPatton** [comment]
i am using webpack ProvidePlugin like this:

```
new webpack.ProvidePlugin({
    React: 'preact-compat',
    ReactDOM: 'preact-compat',
    ReactDOMServer: 'preact-render-to-string',
})
```

I use webpack for both my server and client builds (i bundle my server file) so I would assume that any aliases I set in webpack would be consistent on both the server and client side

Would this not be the case?

**Comment by rossPatton** [comment]
so, i was able to fix this. here is the solution in case anyone else comes across this problem.

in my case, it was because packages with a `/` in the name were not being properly aliased. so when react-ab-test was requiring `react-dom/server` for their server render, it was not being aliased properly

i needed to add the following to my webpack server config (i got this some other thread, can't remember):

```
let nodeModules = {}
fs.readdirSync('node_modules').forEach(function (module) {
  if (module !== '.bin') {
    nodeModules[module] = true;
  }
})

const nodeModulesTransform = function(context, request, callback) {
  // search for a '/' indicating a nested module
  const slashIndex = request.indexOf("/");
  let rootModuleName;
  if (slashIndex == -1) {
    rootModuleName = request;
  } else {
    rootModuleName = request.substr(0, slashIndex);
  }

  // Match for root modules that are in our node_modules
  if (nodeModules.hasOwnProperty(rootModuleName)) {
    callback(null, 'commonjs ' + request);
  } else {
    callback();
  }
}
```

and then in your config object itself add this line:

`externals: [nodeModulesTransform],`
