### ISSUE TITLE
renderToString( h( undefined ) ) returns [object Object]

### ISSUE THREAD

**Issue by meyer** [developit/preact-render-to-string#38]
Not sure if this is a `preact` issue or a `preact-render-to-string` issue, but I’ll put it here for now.

A component I wrote wasn’t being exported properly (long story) and the result was `undefined` instead of a valid component. I thought it was a React alias issue like I saw in a few other issues, but after digging through my bundle I determined that that was not the case.

Seems to me that either `h(undefined)` or `renderToString( h(undefined) )` should throw an error.

**Comment by csantany** [comment]
+1 I have the same problem

**Comment by developit** [comment]
Good point, and I agree - `render(h(undefined))` throws in Preact itself, so it should probably also throw here.

**Comment by developit** [comment]
I've opened #47 that fixes this, if either of you could review that would be great!
