### ISSUE TITLE
dangerouslySetInnerHTML difference in renderToJsxString vs renderToString

### ISSUE THREAD

**Issue by robthehall** [developit/preact-render-to-string#42]
**steps to reproduce**

use dangerouslySetInnerHTML with renderToJsxString

```javascript
> const h = require('preact').h
> console.log(require('preact-render-to-string')(<div dangerouslySetInnerHTML={{__html:'<span>foo</span>'}} />))
<div><span>foo</span></div>
undefined
> console.log(require('preact-render-to-string/jsx')(<div dangerouslySetInnerHTML={{__html:'<span>foo</span>'}} />))
<div
  dangerouslySetInnerHTML={
    Object {
      "__html": "<span>foo</span>"
    }
  }
>
</div>
undefined
```
**expected results**

dangerouslySetInnerHTML "executed" in either render method.

**actual results**

dangerouslySetInnerHTML "executed" only in renderToString, but not renderToJsxString.

**notes**

i'm using [preact-jsx-chai](https://github.com/developit/preact-jsx-chai) and would rather not use dangerouslySetInnerHTML for hardcoded html in my tests. i've tracked down the issue to this library, but feel free to tell me that it should be addressed in the other one. i didn't see a way to tell that library not to use the jsxString render function.

**Comment by developit** [comment]
Ah - I think the attribute serialization in the JSX mode is serializing this, which breaks the rendering later on. I've submitted #46 that should fix it, if you could review :)
