### ISSUE TITLE
Don't return in getComponentName(), if `component.name === 'cl'`

### ISSUE THREAD

**Issue by sampi** [developit/preact-render-to-string#44]
In the same setup as https://github.com/developit/preact-render-to-string/issues/43

I noticed that when `getComponentName()` is called on `inner === true` VNodes, the resolution for the name of the component is often `cl`, even though `proto.displayName` or `proto.name` contains the name of the actual component.

The string `cl` is coming from this line: https://github.com/developit/preact-compat/blob/e25d0607d8a00a3e2f9229f33de4dc0f63c8e931/src/index.js#L405

I could fix this in the code with a simple if inside `getComponentName`:
```js
if (component.name === 'cl') {
	delete component.name;
}
```

Again, I'm not sure if this is happening due to my setup with `preact-compat` or maybe it's related to the `preact-compat-enzyme` but it would be nice to know if this is intended operation of if I'm actually doing something wrong.

Can you help to figure this issue out as well?

**Comment by developit** [comment]
Hmm - `displayName` shouldn't be on the prototype, it should be a property of the component's constructor.  Does changing that fix the issue?

**Comment by developit** [comment]
Ah - it looks like `getComponent()` is looking for displayName on the instance, which is incorrect:

https://github.com/developit/preact-render-to-string/blob/master/src/index.js#L211

Changing it to this should fix the issue (and save some bytes!):

```js
function getComponentName(component) {
	let ctor = component.prototype && component.prototype.constructor;
	return ctor.displayName || ctor.name || getFallbackComponentName(component);
}
```
