### ISSUE TITLE
Default props are not being applied to components, affecting propType validation.

### ISSUE THREAD

**Issue by ctrlplusb** [developit/preact-render-to-string#5]
As originally logged in `preact-compat`: https://github.com/developit/preact-compat/issues/126

**Comment by developit** [comment]
Want me to take a stab at this?

**Comment by ctrlplusb** [comment]
Would appreciate it yes thanks :-)

**Comment by developit** [comment]
Will do.

**Comment by developit** [comment]
Support for `defaultProps` is now added in `2.7.0`.
