### ISSUE TITLE
Allow override of `VOID_ELEMENTS`

### ISSUE THREAD

**Issue by malchata** [developit/preact-render-to-string#53]
In some instances, it's not desirable for certain tags to be treated exclusively as self-closing elements, such as with the `<link>` tag in RSS feeds. It might be useful to allow an additional option in the `renderToString` method to allow users to supply an array of elements they want (or as in this case, don't want) to be treated as self-closing. This may not really be used very much, but in cases where XML is generated, it could be a nice little feature to add.

If you're down, I'm happy to add it. I also see that this has been referenced in a somewhat different way in #52.

**Comment by developit** [comment]
Yup. Sortof a duplicate, but it should be fine.

TBH I know it's ugly, but we could export the global list..

**Comment by developit** [comment]
Let's consolidate on #52.
