### ISSUE TITLE
defaultProps treated differently than in preact

### ISSUE THREAD

**Issue by ftes** [developit/preact-render-to-string#58]
This library behaves differently than preact when dealing with `undefined` prop values.

**Expected behaviour:**
`preact-render-to-string` should behave like `preact`:
1. A default value is set for a prop (`MyComponent.defaultProps.someProp = 'X'`)
2. `undefined` is passed as prop value (`<MyComponent someProp={undefined}/>`)
3. I expect to get the default value within the instantiated component (`console.log(this.props.someProp) >> 'X'`)

**Actual behaviour:**
If `undefined` is passed as prop value, then `this.props.someProp` resolves to `undefined`.

Here you can see how the implementation in `preact` and `preact-render-to-string` differ:
- https://github.com/developit/preact/blob/master/src/vdom/index.js#L47
```js
for (let i in defaultProps) {
  if (props[i]===undefined) {
    props[i] = defaultProps[i];
  }
}
```
- https://github.com/developit/preact-render-to-string/blob/master/src/util.js#L74
```js
let defaultProps = vnode.nodeName.defaultProps,
  props = assign({}, defaultProps || vnode.attributes);
if (defaultProps) assign(props, vnode.attributes);
```

**Comment by developit** [comment]
Hi @ftes! You're right, we're not handling undefined/null correctly in render-to-string.
Would you be interested in submitting a PR? :)

**Comment by ftes** [comment]
Sure thing, PR created @developit

**Comment by developit** [comment]
Thanks, it's out in 3.8.1!
