### ISSUE TITLE
3.8.0 is a breaking change for components without nodenames

### ISSUE THREAD

**Issue by billneff79** [developit/preact-render-to-string#59]
Our builds are failing because `preact-jsx-chai` is using `preact-render-to-string` with a `^3.x` dependency.  With the change in 3.8.0 to no longer cooerce node names to a String before calling the match function here https://github.com/developit/preact-render-to-string/commit/46e72e9c1c5d5a8e1cc3ce33e04460dc724aa81c#diff-1fdf421c05c1140f6d71444ea2b27638L162, any node that does not have a node name now fails the unit test with an exception like:
```
   PhantomJS 2.1.1 (Mac OS X 0.0.0)
    undefined is not an object (evaluating 'y.match')
    p@webpack:///~/preact-render-to-string/dist/jsx.js:1:2667 <- setup-unit.js:4350:141
    p@webpack:///~/preact-render-to-string/dist/jsx.js:1:1643 <- setup-unit.js:4326:34
    p@webpack:///~/preact-render-to-string/dist/jsx.js:1:1643 <- setup-unit.js:4326:34
    exports@webpack:///~/preact-render-to-string/dist/jsx.js:1:8303 <- setup-unit.js:4455:11
    doRender@webpack:///~/preact-jsx-chai/dist/index.js:65:0 <- setup-unit.js:4039:50
    webpack:///~/preact-jsx-chai/dist/index.js:80:0 <- setup-unit.js:4054:25
    /Users/bneff/repos/sports-widget/node_modules/chai/chai.js:5341:38
    webpack:///tests/unit/components/scoreboard/event.js:311:39 <- unit/components/scoreboard/event.js:7005:57
```

I would recommend adding the cooercion back in to a 3.8.1 release and removing it in a 4.0 release if you really want to take it out.

**Comment by developit** [comment]
Yikes! Sorry for the lag there, this should be fixed in 3.8.1.
