### ISSUE TITLE
Calling componentWillMount on render

### ISSUE THREAD

**Issue by mikestead** [developit/preact-render-to-string#6]
This may be under the `preact-compat` domain but relates directly to rendering on the server.

React calls `componentWillMount` on components when server rendering which some libraries depend upon e.g. [isomorphic-style-loader](https://github.com/kriasoft/isomorphic-style-loader). Is this something you'd consider supporting?

Background https://github.com/facebook/react/issues/2674

**Comment by developit** [comment]
Ah, yes - `preact-render-to-string` should definitely be doing this, so you got the right repo!  I can probably try to get this done over the weekend.

**Comment by developit** [comment]
Fixed and released in [preact-render-to-string@2.8.0](https://github.com/developit/preact-render-to-string/releases/tag/2.8.0)! Thanks :)

**Comment by mikestead** [comment]
Awesome, thanks for the fast fix.
