### ISSUE TITLE
The `renderToString` function does not call component's static `getDerivedStateFromProps`

### ISSUE THREAD

**Issue by johnhaitas** [developit/preact-render-to-string#62]
The `renderToString` function calls `componentWillMount()` before rendering. However, per changes to React API, `getDerivedStateFromProps` should take precedence over `componentWillMount()` when available.

Preact already has an issue (https://github.com/developit/preact/issues/1047) tracking what to do with React API changes.

Preact now supports `getDerivedStateFromProps` per this PR - https://github.com/developit/preact/pull/1094

**Comment by developit** [comment]
Good catch!

**Comment by johnhaitas** [comment]
Resolved with 
https://github.com/developit/preact-render-to-string/pull/63 release with https://github.com/developit/preact-render-to-string/releases/tag/4.1.0
