### ISSUE TITLE
Issue: Multiple Renders - Different Data

### ISSUE THREAD

**Issue by dcflow** [developit/preact-render-to-string#69]
Hello,

There seems to be an issue with calling the `render` function multiple times in the same file.

Example: I call the `render` function on the server twice with the same `app` but different `data`:
```
-server.js-

render(<App data={1}>) 
render(<App data={2}>)
```
but the `render` function seem to always pass the data from the first render.
```
-app.js-

console.log(props.data)
// 1
// 1
```
I have tried many scenarios but still same results.

Thank You!

**Comment by developit** [comment]
@dcflow Definitely going to need more information here - renderToString() is completely synchronous as doesn't do any caching, so it's not really possible for it to bleed across invocations. That means there's something else funky happening in your component tree.

**Comment by dcflow** [comment]
Even I can't give much context since it happens once in a while .. so I will close it and open it if I have more info.
