### ISSUE TITLE
Style renders as [object Object] with Preact >5.2.0-beta.0

### ISSUE THREAD

**Issue by rmales** [developit/preact-render-to-string#7]
I guess it may be something to do with this Preact commit: https://github.com/developit/preact/commit/a5b286b0affa2282f70e9834a05095a15a00166b

With Preact 5.6.0:
http://jsfiddle.net/28ckgyzj/3/

With Preact 5.2.0-beta.0:
http://jsfiddle.net/5tzxLy7d/2/

**Comment by developit** [comment]
Good catch! I'll get this fixed ASAP.  We can just use the exact style serialization that was removed Preact.

**Comment by developit** [comment]
Fixed and released in [preact-render-to-string@2.8.0](https://github.com/developit/preact-render-to-string/releases/tag/2.8.0)! Thanks :)
