### ISSUE TITLE
version 5.0.0 is not compatible with preact@8.4.2

### ISSUE THREAD

**Issue by Mizumaki** [developit/preact-render-to-string#76]
Currently when you install preact (`npm install preact`), preact@8.4.2 is installed.

However, when you install preact-render-to-string (`npm install preact-render-to-string`), preact-render-to-string@5.0.0 is installed.

And version 5.0.0 is not compatible with preact@8.4.2, because of VNode format.

Please fix the default version when `npm install preact-render-to-string`.
Thanks.

**Comment by marvinhagemeister** [comment]
@developit We could change the npm tags to make `5.0.0` point to `next` and the `4.x` release point to `latest`

**Comment by developit** [comment]
We'll have to re-tag. The peerDependencies are already set to limit render-to-string@5 to use with preact 10+:
https://github.com/developit/preact-render-to-string/blob/master/package.json#L61-L63

Problem is that 5.0.0 wasn't released as an alpha.

**Comment by developit** [comment]
This has been addressed. Usage with `preact@next` now requires installing `preact-render-to-string@next`:
<img width="369" alt="Screen Shot 2019-03-14 at 3 34 23 PM" src="https://user-images.githubusercontent.com/105127/54386144-b21b6f00-466e-11e9-96b2-856e269e770a.png">
